#!/usr/bin/env python3
import sys
import os
import subprocess
import shutil
import zipfile
sys.path.insert(1, "/usr/lib/waydroid")
import tools as waydroid


previous_images_path = "/userdata/system-data/etc/waydroid-extra/images"


# make / rw
was_rw_root = False
if not os.path.exists("/etc/waydroid-extra"):
    root = os.statvfs('/')
    if root.f_flag & os.ST_RDONLY:
        subprocess.run(["mount", "-o", "remount,rw", "/"])
    else:
        was_rw_root = True

# still needed for bind-mount to trick "waydroid init" here
os.makedirs("/etc/waydroid-extra", exist_ok=True)

# we're done messing with rootfs
if not was_rw_root:
    subprocess.run(["mount", "-o", "remount,ro", "/"])


# any images setup by Waydroid Helper <=3.2.0 are likely unstable, clean them up and setup the new ones below
if os.path.exists(previous_images_path):
    shutil.rmtree(previous_images_path)

# avoid potential old /etc/system-image/writable-paths artifact
if os.path.ismount("/etc/waydroid-extra"):
    subprocess.run(["umount", "/etc/waydroid-extra"])

# trick "waydroid init" etc for the remainder of this script
os.makedirs("/var/lib/waydroid/images", exist_ok=True)
subprocess.run(["mount", "--bind", "/var/lib/waydroid", "/etc/waydroid-extra"])


# prep for using waydroid download func similar to tools/__init__.py
args = waydroid.helpers.arguments()
waydroid.prep_args(args)
waydroid.helpers.logging.init(args)

if os.path.exists("/var/lib/waydroid/images/vendor.img"):
    print("Already initialized")
    sys.exit(0)

images_url = "https://volla.tech/filedump/waydroid-16"
images_date = "20260908"
for img in [f"waydroid_arm64_only-system-{images_date}", f"waydroid_arm64_only-vendor-{images_date}"]:
    downloaded_zip = waydroid.helpers.http.download(args, f"{images_url}/{img}.zip", os.path.basename(f"{img}.zip"), cache=False)
    print(f"Validating {'vendor' if 'vendor' in img else 'system'} image") # stub
    print("Extracting to /var/lib/waydroid/images")
    with zipfile.ZipFile(downloaded_zip, 'r') as zip_ref:
        zip_ref.extractall("/var/lib/waydroid/images")
    os.remove(downloaded_zip)


# start using downloaded custom images
ret = subprocess.run(["waydroid", "init", "-f"]).returncode
if ret != 0:
    sys.exit(ret)

# finally keep working by always searching for images in persistent-across-OTAs /var/lib/waydroid/images
sys.exit(subprocess.run(["sed", "-i", "s:/etc/waydroid-extra/images:/var/lib/waydroid/images:", "/var/lib/waydroid/waydroid.cfg"]).returncode)
