#!/usr/bin/env python3
import sys
import os
import subprocess
import shutil
import zipfile
sys.path.insert(1, "/usr/lib/waydroid")
import tools as waydroid


def ver(v):
    return tuple(map(int, (v.split("."))))


waydroid_ver = subprocess.check_output(["waydroid", "--version"]).decode()
wrapper_script_needed = ver(waydroid_ver) < ver("1.5.0")
wrapper_script_exists = os.path.exists("/usr/local/bin/waydroid")
wrapper_script_changing = wrapper_script_needed is not wrapper_script_exists
previous_images_path = "/userdata/system-data/etc/waydroid-extra/images"


# make / rw
was_rw_root = False
if not os.path.exists("/etc/waydroid-extra") or wrapper_script_changing:
    root = os.statvfs('/')
    if root.f_flag & os.ST_RDONLY:
        subprocess.run(["mount", "-o", "remount,rw", "/"])
    else:
        was_rw_root = True

# still needed for bind-mount to trick "waydroid init" here
os.makedirs("/etc/waydroid-extra", exist_ok=True)

if wrapper_script_needed and not wrapper_script_exists:
    # workaround having to "double-launch" every UI action
    with open("/usr/local/bin/waydroid", "w") as f:
        f.write("""\
#!/bin/sh
case "$1" in
show-full-ui) DOUBLE_LAUNCH=1 ;;
app)
    case "$2" in
    launch|intent) DOUBLE_LAUNCH=1 ;;
    esac
esac

if [ "$(pgrep -f '/usr/bin/waydroid (show-full-ui|app (launch|intent))')" ]; then
    unset DOUBLE_LAUNCH
fi

[ -z "$DOUBLE_LAUNCH" ] && exec /usr/bin/waydroid "$@"

/usr/bin/waydroid show-full-ui &
sleep 1
/usr/bin/waydroid show-full-ui
wait
""")
    os.chmod("/usr/local/bin/waydroid", 0o755)
elif not wrapper_script_needed and wrapper_script_exists:
    os.remove("/usr/local/bin/waydroid")

# we're done messing with rootfs
if not was_rw_root:
    subprocess.run(["mount", "-o", "remount,ro", "/"])


# any images setup by Waydroid Helper <=3.2.0 are likely unstable, clean them up and setup the new ones below
if os.path.exists(previous_images_path):
    shutil.rmtree(previous_images_path)

# avoid potential old /etc/system-image/writable-paths artifact
if os.path.ismount("/etc/waydroid-extra"):
    subprocess.run(["umount", "/etc/waydroid-extra"])

# trick "waydroid init" etc for the remainder of this script
os.makedirs("/var/lib/waydroid/images", exist_ok=True)
subprocess.run(["mount", "--bind", "/var/lib/waydroid", "/etc/waydroid-extra"])


# prep for using waydroid download func similar to tools/__init__.py
args = waydroid.helpers.arguments()
args.work = waydroid.config.defaults["work"]
args.sudo_timer = True
args.timeout = 1800
args.log = args.work + "/waydroid.log"
waydroid.helpers.logging.init(args)

if os.path.exists("/var/lib/waydroid/images/vendor.img"):
    print("Already initialized")
    sys.exit(0)

images_url = "https://sourceforge.net/projects/waydroid/files/images"
system_variant = "GAPPS" if "GAPPS" in sys.argv else "VANILLA"
images_date = "20250614"
for img in [f"system/lineage/waydroid_arm64/lineage-20.0-{images_date}-{system_variant}-waydroid_arm64-system",
            f"vendor/waydroid_arm64/lineage-20.0-{images_date}-HALIUM_13-waydroid_arm64-vendor"]:
    downloaded_zip = waydroid.helpers.http.download(args, f"{images_url}/{img}.zip/download", os.path.basename(f"{img}.zip"), cache=False)
    print(f"Validating {'vendor' if 'vendor' in img else 'system'} image") # stub
    print("Extracting to /var/lib/waydroid/images")
    with zipfile.ZipFile(downloaded_zip, 'r') as zip_ref:
        zip_ref.extractall("/var/lib/waydroid/images")
    os.remove(downloaded_zip)


# start using downloaded custom images
ret = subprocess.run(["waydroid", "init", "-f"]).returncode
if ret != 0:
    sys.exit(ret)

# finally keep working by always searching for images in persistent-across-OTAs /var/lib/waydroid/images
subprocess.run(["sed", "-i", "s:/etc/waydroid-extra/images:/var/lib/waydroid/images:", "/var/lib/waydroid/waydroid.cfg"])
